// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace app.Models
{

    internal class ByeResponse
   {

        [JsonProperty("cmd")]
        public string Cmd { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
      internal bool IsValid()
      {
         return Cmd == "send" && this.Type == "bye";
      }
      [JsonProperty("originatingClient")]
      public string OriginatingClient { get; set; }
      internal string ResponseString(string clientId)
      {
         OriginatingClient = clientId;
         return JsonConvert.SerializeObject(this, Formatting.Indented);
      }
   }

}
