// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace app.Models
{

    internal class CandidateResponse
    {

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("label")]
        public int Label { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("candidate")]
        public string Candidate { get; set; }

      internal bool IsValid()
      {
         return Type == "candidate";
      }
      internal string ResponseString(string clientId)
      {
         string candidatePayLoad = JsonConvert.SerializeObject(this, Formatting.Indented);
       
         MsgTypeResponse cmdMsgPayLoad = new MsgTypeResponse
         {
            Type = Type,
            Msg = candidatePayLoad,
            //OriginatingClient= clientId
         };

         return JsonConvert.SerializeObject(cmdMsgPayLoad, Formatting.Indented);
      }
   }

}
