// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace app.Models
{

    internal class MessageResponse
    {

        [JsonProperty("cmd")]
        public string Cmd { get; set; }

        [JsonProperty("msg")]
        public string Msg { get; set; }
      internal bool IsValid()
      {
         return Cmd == "send" && this.Msg != null  && this.Msg != "bye";
      }

      internal string ResponseString()
      {
         SdpResponse sdpResponse = JsonConvert.DeserializeObject<SdpResponse>(this.Msg);
         if (sdpResponse.IsValid())
         {
            return sdpResponse.ResponseString();
         }
         CandidateResponse candidateResponse = JsonConvert.DeserializeObject<CandidateResponse>(this.Msg);
         if (candidateResponse.IsValid())
         {
            return candidateResponse.ResponseString();
         }
         return string.Empty;
      }
   }

}
