// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;
namespace app.Models
{

   internal class RegisterResponse
    {

        [JsonProperty("cmd")]
        public string Cmd { get; set; }

        [JsonProperty("roomid")]
        public string Roomid { get; set; }

        [JsonProperty("clientid")]
        public string Clientid { get; set; }
      internal bool IsValid()
      {
         return Cmd == "register"  /*&& this.Roomid != null && this.Clientid != null*/;
      }

      internal string ResponseString()
      {

         //RoomClient roomClientResponse = new RoomClient
         //{
         //   Clientid = this.Clientid,
         //   Roomid = this.Roomid,
         //};
         //var msg = JsonConvert.SerializeObject(roomClientResponse, Formatting.Indented);

         MsgTypeResponse msgTypeResponse = new MsgTypeResponse
         {
            Type = "register",
            //Msg = msg
         };

         return JsonConvert.SerializeObject(msgTypeResponse, Formatting.Indented);
      }
   }

}
