// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace app.Models
{

   internal class RoomClient
   {
      [JsonProperty("roomid")]
      public string Roomid { get; set; }

      [JsonProperty("clientid")]
      public string Clientid { get; set; }
   }

}
