// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace app.Models
{

    internal class SdpResponse
    {

        [JsonProperty("sdp")]
        public string Sdp { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
      internal bool IsValid()
      {
         return Type == "sdp" && !string.IsNullOrEmpty(this.Sdp);
      }

      internal string ResponseString(string clientId)
      {
         MsgTypeResponse typeResponse = new MsgTypeResponse
         {
            Msg = Sdp,
            Type = Type,
            //OriginatingClient = clientId
         };

          return JsonConvert.SerializeObject(typeResponse, Formatting.Indented);
      }
   }

}
